/**:
  ros__parameters:
    use_sim_time: false # Set to `true` only if there is a publisher for the simulated clock to the `/clock` topic. Normally used in simulation mode.

    general:
      camera_model: 'zedx'
      camera_name: 'zedx'
      grab_resolution: 'HD1080' # The native camera grab resolution. 'HD1200', 'HD1080', 'SVGA', 'AUTO'
      grab_frame_rate: 15 # ZED SDK internal grabbing rate (HD1200/HD1080: 60, 30, 15 - SVGA: 120, 60, 30, 15)
      camera_timeout_sec: 5
      camera_max_reconnect: 5
      camera_flip: false
      serial_number: 0 # usually overwritten by launch file
      pub_resolution: "NATIVE" # The resolution used for output. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
      pub_downscale_factor: 2.0 # rescale factor used to rescale image before publishing when 'pub_resolution' is 'CUSTOM'
      pub_frame_rate: 15.0 # frequency of publishing of visual images and depth images
      gpu_id: 0 # GPU ID to be used by the ZED SDK on Jetson platforms
      optional_opencv_calibration_file: "" # Optional path where the ZED SDK can find a file containing the calibration information of the camera computed by OpenCV. Read the ZED SDK documentation for more information: https://www.stereolabs.com/docs/api/structsl_1_1InitParameters.html#a9eab2753374ef3baec1d31960859ba19

    simulation:
      sim_enabled: false # Set to `true` to enable the simulation mode and connect to a simulation server

    video:
      brightness: 4 # [DYNAMIC] Not available for ZED X/ZED X Mini
      contrast: 4 # [DYNAMIC] Not available for ZED X/ZED X Mini
      hue: 0 # [DYNAMIC] Not available for ZED X/ZED X Mini
      saturation: 4 # [DYNAMIC]
      sharpness: 4 # [DYNAMIC]
      gamma: 8 # [DYNAMIC]
      auto_exposure_gain: true # [DYNAMIC]
      exposure: 80 # [DYNAMIC]
      gain: 80 # [DYNAMIC]
      auto_whitebalance: true # [DYNAMIC]
      whitebalance_temperature: 42 # [DYNAMIC] - [28,65] works only if `auto_whitebalance` is false
      exposure_time: 16000 # Defines the real exposure time in microseconds. Recommended to control manual exposure (instead of `video.exposure` setting)
      auto_exposure_time_range_min: 28 # Defines the minimum range of exposure auto control in micro seconds
      auto_exposure_time_range_max: 30000 # Defines the maximum range of exposure auto control in micro seconds
      exposure_compensation: 50 # Defines the Exposure-target compensation made after auto exposure. Reduces the overall illumination target by factor of F-stops. Values range is [0 - 100]. Default value is 50, i.e. no compensation applied
      analog_gain: 1255 # Defines the real analog gain (sensor) in mDB. Range [1000-16000]. Recommended to control manual sensor gain (instead of `video.gain` setting)
      auto_analog_gain_range_min: 1000 # Defines the minimum range of sensor gain in automatic control
      auto_analog_gain_range_max: 16000 # Defines the maximum range of sensor gain in automatic control
      digital_gain: 1 # Defines the real digital gain (ISP) as a factor. Range [1-256]. Recommended to control manual ISP gain (instead of `video.gain` setting)
      auto_digital_gain_range_min: 1 # Defines the minimum range of digital ISP gain in automatic control
      auto_digital_gain_range_max: 256 # Defines the maximum range of digital ISP gain in automatic control
      denoising: 50 # Defines the level of denoising applied on both left and right images. Range [0-100]

    svo:
      svo_loop: false # Enable loop mode when using an SVO as input source
      svo_realtime: true # if true the SVO will be played trying to respect the original framerate eventually skipping frames, otherwise every frame will be processed respecting the `pub_frame_rate` setting

    depth:
      depth_mode: "ULTRA"
      min_depth: 0.3 # Min: 0.3, Max: 3.0
      max_depth: 10.0 # Max: 20.0

    sensors:
      publish_imu_tf: false # [usually overwritten by launch file] enable/disable the IMU TF broadcasting
      sensors_image_sync: false # Synchronize Sensors messages with latest published video/depth message
      sensors_pub_rate: 1. # frequency of publishing of sensors data. MAX: 400. - MIN: grab rate

    region_of_interest:
      automatic_roi: false

    pos_tracking:
      pos_tracking_enabled: false

    gnss_fusion:
      gnss_fusion_enabled: false

    mapping:
      mapping_enabled: false

    object_detection:
      od_enabled: false

    body_tracking:
      bt_enabled: false # True to enable Body Tracking

    stream_server:
      stream_enabled: false

    advanced: # WARNING: do not modify unless you are confident of what you are doing
      # Reference documentation: https://man7.org/linux/man-pages/man7/sched.7.html
      thread_sched_policy: "SCHED_BATCH" # 'SCHED_OTHER', 'SCHED_BATCH', 'SCHED_FIFO', 'SCHED_RR' - NOTE: 'SCHED_FIFO' and 'SCHED_RR' require 'sudo'
      thread_grab_priority: 50 # ONLY with 'SCHED_FIFO' and 'SCHED_RR' - [1 (LOW) z-> 99 (HIGH)] - NOTE: 'sudo' required
      thread_sensor_priority: 70 # ONLY with 'SCHED_FIFO' and 'SCHED_RR' - [1 (LOW) z-> 99 (HIGH)] - NOTE: 'sudo' required
      thread_pointcloud_priority: 60 # ONLY with 'SCHED_FIFO' and 'SCHED_RR' - [1 (LOW) z-> 99 (HIGH)] - NOTE: 'sudo' required

    debug:
      sdk_verbose: 1 # Set the verbose level of the ZED SDK
      debug_common: false
      debug_sim: false
      debug_video_depth: false
      debug_camera_controls: false
      debug_point_cloud: false
      debug_positional_tracking: false
      debug_gnss: false
      debug_sensors: false
      debug_mapping: false
      debug_terrain_mapping: false
      debug_object_detection: false
      debug_body_tracking: false
      debug_roi: false
      debug_streaming: false
      debug_advanced: false